services:
  postgresql-super:
    image: bitnami/postgresql:latest
    container_name: postgresql-super
    environment:
      - POSTGRESQL_USERNAME=super
      - POSTGRESQL_PASSWORD=super
      - POSTGRESQL_DATABASE=super
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
volumes:
  postgresql_data: